#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "43f2e113c6ed41688d16013fae4c1799" }
]

[assets]
directory = "./public"
